##
## You provide this to build your docker image,
##
build:
	docker build -t worker:v1 .

# After building your image, go write up the deployment and tell it to use
# this image and pull it from my eliberumen27 Docker Hub

##deployment:
##	kubectl create deployment worker --image=
