##
## You provide this
##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-frontend
spec:
  selector:
    matchLabels:
      app: rest-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-frontend
    spec:
      containers:
      - name: rest
        image: eliberumen27/rest:v1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: REDIS_HOST
            value: redis
          - name: RABBITMQ_HOST
            value: rabbitmq
        ports:
        - containerPort: 5000
