##
## You provide this
##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-frontend
spec:
  selector:
    matchLabels:
      app: rest-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-frontend
    spec:
      containers:
      - name: rest
        image: eliberumen27/spotify-rest:v1 # specify the correct front-end image that I have in Hub
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: REDIS_HOST
            value: redis
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: MYSQL_HOST
            value: mysql
          - name: SPOTIFY_CLIENT_ID
            value: "848e3bdfd0a549158229482146ada46f"
          - name: SPOTIFY_CLIENT_SECRET
            value: "67ae28d9bb184d7bac670f9a080b536d"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "Spotify-Voice-Search-42d35eee1902.json"
        ports:
        - containerPort: 5000
